# Generated by Django 4.2.6 on 2023-11-18 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_role_profile_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
